#!/bin/sh

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

echo "avahi:x:136:" >> "/etc/group"
echo "avahi:x:127:136:Avahi mDNS daemon,,,:/run/avahi-daemon:/usr/sbin/nologin" >> "/etc/passwd"
log_begin_msg "Sleeping for 5 seconds, then starting avahi"
sleep 5
log_end_msg

log_begin_msg "starting avahi-daemon in background"
/usr/sbin/avahi-daemon &


